import = [
	"./themes/themes/nord.toml"
]

#[shell]
#program="/bin/zsh"

[font]

#normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
#italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
#bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

#normal = { family = "Iosevka Fixed", style = "Regular" }
#bold = { family = "Iosevka Fixed", style = "Bold" }
#italic = { family = "Iosevka Fixed", style = "Italic" }
#bold_italic = { family = "Iosevka Fixed", style = "Bold Italic" }

# Ubuntu Mono
#normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
#bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
#italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
#bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

# Space Mono
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
bold = { family = "SpaceMono Nerd Font", style = "Bold" }
italic = { family = "SpaceMono Nerd Font", style = "Italic" }
bold_italic = { family = "SpaceMono Nerd Font", style = "Bold Italic" }

size = 8.0
offset = {x = 0, y = -3}

[bell]
animation = "Ease"
duration = 300
color = "#d8dee9"

[colors]

[colors.primary]
foreground="#D8DEE9"
background="#2E3440"
[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a4be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"
[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a4be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"
[cursor]
style = {shape = "Beam", blinking = "Always"}
unfocused_hollow = false
blink_interval = 500
blink_timeout = 30

[mouse]
hide_when_typing = true
bindings = [
    {mouse = "Middle", action = "Paste"}
]

[scrolling]
multiplier = 4

[window]
opacity = 1.0
#decorations = 'none'
title = 'Alacritty'
dynamic_title = true
padding = {x = 9, y = 9}
dynamic_padding = true
startup_mode = "Windowed"
